from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import DateTime, ForeignKey, String, func

from app.db.base import Base


class WebhookEvent(Base):
    '''
    Represents a webhook event generated by the system.

    In this MVP:
    - A webhook event is created after a payment succeeds of fails.
    - The event can later be delivered to the merchant webhook URL.
    - Delivery status is tracked so failures can be retried later.
    '''

    __tablename__ = "webhook_events"

    id: Mapped[int] = mapped_column(primary_key=True)

    # Merchant that should receive this webhook event
    merchant_id: Mapped[int] = mapped_column(ForeignKey("merchants.id"))
    
    # Related payment intent
    payment_intent_id: Mapped[int] = mapped_column(
        ForeignKey("payment_intents.id"),
        nullable=False,
    )

    # Event type, e.g. payment.succeeded or payment.failed
    event_type: Mapped[str] = mapped_column(String(100), nullable=False)

    # Serialized webhook payload
    payload: Mapped[str] = mapped_column(String, nullable=False)

    # Delivery state: pending | delivered | failed
    delivery_status: Mapped[str] = mapped_column(String(50), nullable=False, default="pending")

    created_at: Mapped[DateTime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    